name: websocket_manager
description: A Flutter plugin for Android and iOS supports websocket connection
version: 1.0.0-nullsafety
homepage: https://github.com/Zakhrov/flutter_websocket_plugin.git

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: br.com.engapp.websocket_manager
        pluginClass: WebsocketManagerPlugin
      ios:
        pluginClass: WebsocketManagerPlugin
